# Kew-MNIST Synthetic Enhancement Configuration

# Data settings
data:
  original_data_path: "data/kew_mnist_original"
  synthetic_data_path: "data/kew_mnist_synthetic"
  processed_data_path: "data/processed"
  image_size: 500
  batch_size: 128
  test_split: 0.3
  random_seed: 42
  
# Model architecture
model:
  input_shape: [500, 500, 1]
  num_classes: 6
  filters: [64, 128, 256]
  kernel_size: 3
  pool_size: [4, 4, 2]
  dropout_rates: [0.3, 0.4, 0.5]
  dense_units: [256, 128]
  l2_regularization: 0.001
  activation: "leaky_relu"
  
# Training settings
training:
  epochs: 20
  learning_rate: 0.0001
  patience: 5
  min_delta: 0.001
  reduce_lr_factor: 0.5
  reduce_lr_patience: 3
  class_weight_multipliers:
    flower: 1.0
    fruit: 1.0
    leaf: 1.0
    plant_tag: 0.16
    stem: 1.0
    whole_plant: 1.0
    
# Paths
paths:
  models_dir: "models"
  results_dir: "results"
  logs_dir: "logs"
  
